-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campeonato
(
    id integer NOT NULL,
    campeonato character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campeonato_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jogo
(
    id integer NOT NULL,
    madante_id integer NOT NULL,
    visitante_id integer NOT NULL,
    data date NOT NULL,
    status integer NOT NULL,
    gols_mandante integer NOT NULL,
    gols_visitante integer NOT NULL,
    campeonato_id integer,
    CONSTRAINT jogo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jogo_status
(
    id integer NOT NULL,
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT jogo_status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.times
(
    id integer NOT NULL,
    "time" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT times_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.jogo
    ADD CONSTRAINT "campeonato_FK" FOREIGN KEY (campeonato_id)
    REFERENCES public.campeonato (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.jogo
    ADD CONSTRAINT "mandante_FK" FOREIGN KEY (madante_id)
    REFERENCES public.times (id) MATCH FULL
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.jogo
    ADD CONSTRAINT "status_FK" FOREIGN KEY (status)
    REFERENCES public.jogo_status (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.jogo
    ADD CONSTRAINT "visitante_FK" FOREIGN KEY (visitante_id)
    REFERENCES public.times (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

END;